---
- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

- name: Install Base Packages
  become: yes
  apt:
    pkg:
      - build-essential
      - cmake
      - gdb
      - python3-dev
      - python3-pip
      - git
      - libssl-dev
      - libffi-dev
      - wget
      - g++-multilib
      - p7zip-full
      - xz-utils
      - zip
      - openjdk-8-jdk
      - fish
      - tmux
      - curl
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - llvm
      - libncurses5-dev
      - libncursesw5-dev
      - tk-dev
      - liblzma-dev
      - python-openssl
      - fortune
      - cinnamon-desktop-environment
      - lightdm
      - dkms
      - module-assistant
      - apt-transport-https
      - gnupg2
