---
- name: Create the ~/tools directory
  file:
    path: '{{ ansible_env.HOME }}/tools'
    state: directory
    mode: '0755'

- name: Create the ~/tools/bin directory
  file:
    path: '{{ ansible_env.HOME }}/tools/bin'
    state: directory
    mode: '0755'

- name: Download cloudflared
  unarchive:
    src: https://bin.equinox.io/c/VdrWdbjqyF/cloudflared-stable-linux-amd64.tgz
    dest: '{{ ansible_env.HOME }}/tools/bin/'
    remote_src: yes
    mode: '0744'

- name: Downloading neovim
  get_url:
    url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
    dest: '{{ ansible_env.HOME}}/tools/bin/nvim'
    mode: 0755
