---
- name: Create the ~/tools directory
  file:
    path: '{{ ansible_env.HOME }}/tools'
    state: directory
    mode: '0755'

- name: Create the ~/tools/ansible_bin directory
  file:
    path: '{{ ansible_env.HOME }}/tools/ansible_bin'
    state: directory
    mode: '0755'

- name: Clone grabbag repo
  git:
    repo: https://github.com/Ayrx/grabbag.git
    dest: '{{ ansible_env.HOME }}/grabbag'
    depth: 1
    update: yes

- name: Install grabbag
  shell: '{{ ansible_env.HOME }}/grabbag/install.sh'
